### ISSUE TITLE
Composer Install - Could Not Find Package

### ISSUE THREAD

**Issue by pixeldrift64** [PhpGt/WebEngine#298] opened 2018-12-20 18:52 UTC
Not sure if I'm doing something wrong, as I don't use composer often, but I'm trying to follow the getting started guide and when I try to run the command:

`composer global require phpgt/installer`

I get the following error:

`Could not find a matching version of package phpgt/installer. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).`

Any ideas?

**Comment by g105b** [comment] 2019-02-05 21:55
Fixed in latest release.

This issue was caused by the `phpgt/installer` and its dependencies not being released as "stable", so you would have had to have set your Composer's minimum stability to "dev"... not any more.

Have fun trying out WebEngine. Docs will be online at https://www.php.gt soon!

**Closed by g105b** 2019-02-05 21:55 UTC
